shoot:
    useHardware: true
    targets:
        - name: Groot
          pin: 19
          updown: up
          channel: 0x0
          up: 4932
          down: 2096
        - name: GrootLaser
          pin: 12
          updown: down
          channel: 0x0
          up: 4932
          down: 2096
        - name: Drax
          pin: 13
          updown: up
          channel: 0x2
          up: 5248
          down: 8960
        - name: DraxLaser
          pin: 16
          updown: down
          channel: 0x2
          up: 5248
          down: 8960
        - name: StarLord
          pin: 6
          updown: up
          channel: 0x1
          up: 6084
          down: 2816
        - name: StarLordLaser
          pin: 21
          updown: down
          channel: 0x1
          up: 6084
          down: 2816
    log:
        level: debug
        levels: 
            emergency: 0
            error: 3
            warning: 4
            info: 6
            debug: 7
            trace: 8
        colors: 
            emergency: red
            error: red
            warn: yellow
            info: white
            debug: green
            trace: blue